-- Abu Dhabi Client Tracker — Supabase Schema
-- Run this entire file in the Supabase SQL Editor

CREATE TABLE IF NOT EXISTS companies (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  address TEXT,
  website TEXT,
  maps TEXT,
  procurement_email TEXT,
  office_phone TEXT,
  procurement_officer TEXT,
  notes TEXT,
  physical_meeting_1 BOOLEAN DEFAULT FALSE,
  call_1 BOOLEAN DEFAULT FALSE,
  call_2 BOOLEAN DEFAULT FALSE,
  call_3 BOOLEAN DEFAULT FALSE,
  physical_meeting_2 BOOLEAN DEFAULT FALSE,
  status TEXT,
  assigned_to TEXT,
  added_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pending_companies (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  city TEXT,
  address TEXT,
  website TEXT,
  maps TEXT,
  procurement_email TEXT,
  office_phone TEXT,
  procurement_officer TEXT,
  notes TEXT,
  added_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- Disable RLS for simplicity (protected by password gate in frontend)
ALTER TABLE companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE pending_companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings DISABLE ROW LEVEL SECURITY;

-- Default settings
INSERT INTO app_settings VALUES ('categories','["Interior Companies", "Design Companies", "Consultants", "Hotels", "Holding Companies", "Royal HH Offices", "FF&E Buying Companies", "Joinery Companies"]') ON CONFLICT(key) DO NOTHING;
INSERT INTO app_settings VALUES ('emirates','["Abu Dhabi", "Dubai", "Sharjah", "Ajman", "Umm Al Quwain", "Ras Al Khaimah", "Fujairah"]') ON CONFLICT(key) DO NOTHING;
INSERT INTO app_settings VALUES ('assignees','["Majen", "Aashel"]') ON CONFLICT(key) DO NOTHING;

-- Migrate 34 approved companies
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Arcave','Interior Companies','Abu Dhabi','https://arcave.ae','https://maps.google.com/?q=Arcave+Architecture+Abu+Dhabi','','+971 50 353 2545','','Verified: Al Danah, Zone 1 — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Interspace Interiors LLC','Interior Companies','Abu Dhabi','https://ispace.ae','https://maps.google.com/?q=Interspace+Interiors+LLC+Abu+Dhabi','','+971 2 676 5430','','Verified: Al Zahiyah, opposite Abu Dhabi Mall — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Eminent Interio','Interior Companies','Abu Dhabi','https://eminentinterio.com','https://maps.google.com/?q=Eminent+Interio+Mussafah+Abu+Dhabi','','+971 56 775 6776','','Verified: Musaffah M45, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Gensler Abu Dhabi','Design Companies','Abu Dhabi','https://gensler.com','https://maps.google.com/?q=Gensler+Abu+Dhabi','','+971 2 696 3400','','Verified: Abu Dhabi Mall East Tower, Al Zahiyah — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Dewan Architects & Engineers','Design Companies','Abu Dhabi','https://dewan-architects.com','https://maps.google.com/?q=Dewan+Architects+Engineers+Abu+Dhabi','','+971 2 681 5777','','Verified: Al Marina, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('MZ Architects','Design Companies','Abu Dhabi','https://mz-architects.com','https://maps.google.com/?q=MZ+Architects+Soho+Square+Abu+Dhabi','','+971 2 635 0002','','Verified: Soho Square, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Aperture Design Studio','Design Companies','Abu Dhabi','https://aperturedesignstudio.com','https://maps.google.com/?q=Aperture+Design+Studio+Abu+Dhabi','','+971 2 641 3509','','Verified: Al Saadah, Zone 1, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('United Design International (UDI)','Consultants','Abu Dhabi','https://udi.ae','https://maps.google.com/?q=United+Design+International+Abu+Dhabi','','+971 2 207 2220','','Verified: Dusit Thani Complex, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Akkad Consultants','Consultants','Abu Dhabi','https://akkadconsultants.com','https://maps.google.com/?q=Akkad+Consultants+Architecture+Abu+Dhabi','','+971 2 562 0979','','Verified: Al Danah, Zone 1, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Gemaco Interiors','Consultants','Abu Dhabi','https://gemacointeriors.com','https://maps.google.com/?q=Gemaco+Interiors+Abu+Dhabi','','+971 2 633 9100','','Verified: Airport Rd, Al Danah, Zone 1, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Shaam Architects','Consultants','Abu Dhabi','https://shaamarchitects.com','https://maps.google.com/?q=Shaam+Architects+Al+Falah+Abu+Dhabi','','+971 50 979 3060','','Verified: Al Falah St, Zone 1, Abu Dhabi — confirmed via Google Maps. Phone corrected.',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Emirates Palace Mandarin Oriental','Hotels','Abu Dhabi','https://mandarinoriental.com/en/abu-dhabi','https://maps.google.com/?q=Emirates+Palace+Mandarin+Oriental+Abu+Dhabi','','+971 2 690 9000','','Verified: West Corniche Road, Al Ras Al Akhdar — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Four Seasons Hotel Abu Dhabi at Al Maryah Island','Hotels','Abu Dhabi','https://fourseasons.com/abudhabi','https://maps.google.com/?q=Four+Seasons+Hotel+Abu+Dhabi+Al+Maryah+Island','','+971 2 333 2222','','Verified: Al Maryah Island, inside The Galleria — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Ritz-Carlton Abu Dhabi Grand Canal','Hotels','Abu Dhabi','https://ritzcarlton.com/en/hotels/auh-rc','https://maps.google.com/?q=Ritz+Carlton+Abu+Dhabi+Grand+Canal','','+971 2 818 8888','','Verified: Al Maqta Area, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('St. Regis Saadiyat Island Resort','Hotels','Abu Dhabi','https://marriott.com/en-us/hotels/auhxr-the-st-regis-saadiyat-island-resort-abu-dhabi','https://maps.google.com/?q=St+Regis+Saadiyat+Island+Resort+Abu+Dhabi','','+971 2 498 8888','','Verified: Saadiyat Island, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Conrad Abu Dhabi Etihad Towers','Hotels','Abu Dhabi','https://hilton.com/en/hotels/auhcihi-conrad-abu-dhabi-etihad-towers','https://maps.google.com/?q=Conrad+Abu+Dhabi+Etihad+Towers','','+971 2 811 5555','','Verified: Corniche Rd, Al Bateen, Abu Dhabi. NOTE: Rebranded from Jumeirah to Conrad (Hilton). Confirmed via Google Maps.',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Novotel Abu Dhabi Gate','Hotels','Abu Dhabi','https://all.accor.com/hotel/B373/index.en.shtml','https://maps.google.com/?q=Novotel+Abu+Dhabi+Gate','','+971 2 508 9999','','Verified: Al Maqta St, Rabdan, Abu Dhabi. Phone corrected from 408 to 508 9999.',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Fairmont Bab Al Bahr','Hotels','Abu Dhabi','https://fairmont.com/bab-al-bahr-abu-dhabi','https://maps.google.com/?q=Fairmont+Bab+Al+Bahr+Abu+Dhabi','','+971 2 654 3333','','Verified: Khor Al Maqta, Rabdan, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('ADQ (Abu Dhabi Developmental Holding Company)','Holding Companies','Abu Dhabi','https://adq.ae','https://maps.google.com/?q=ADQ+Capital+Gate+Abu+Dhabi','','+971 2 204 0000','','Verified: Capital Gate, Al Rawdah, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('International Holding Company (IHC)','Holding Companies','Abu Dhabi','https://ihcuae.com','https://maps.google.com/?q=IHC+Al+Muntazah+Abu+Dhabi','','+971 2 644 8090','','Verified: Al Muntazah, Ministries Complex, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Aldar Properties','Holding Companies','Abu Dhabi','https://aldar.com','https://maps.google.com/?q=Aldar+Properties+Yas+Island+Abu+Dhabi','','800 25327','','Verified: Yas Mall, Yas Island, Abu Dhabi — confirmed via Google Maps. Toll-free 800 25327.',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('ADNEC Group','Holding Companies','Abu Dhabi','https://adnec.ae','https://maps.google.com/?q=ADNEC+Centre+Abu+Dhabi','','+971 2 444 6900','','Verified: Al Khaleej Al Arabi St, Al Rawdah, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('TAQA (Abu Dhabi National Energy Company)','Holding Companies','Abu Dhabi','https://taqa.com','https://maps.google.com/?q=TAQA+Abu+Dhabi+National+Energy+Company','','+971 2 691 4900','','Verified: Al Maryah Island, The Galleria, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Mubadala Investment Company','Holding Companies','Abu Dhabi','https://mubadala.com','https://maps.google.com/?q=Mubadala+Investment+Company+Abu+Dhabi','','+971 2 413 4000','','Verified: Mamoura Buildings, Muroor Road, Abu Dhabi. Phone corrected to 413 4000.',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Abu Dhabi Executive Council','Royal HH Offices','Abu Dhabi','https://abudhabi.ae','https://maps.google.com/?q=Abu+Dhabi+Executive+Office','','+971 2 668 8888','','Verified: Saif Ghubash St, Abu Dhabi — confirmed via Google Maps as Abu Dhabi Executive Office',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Sheikh Mansour Bin Zayed Private Office','Royal HH Offices','Abu Dhabi','','https://maps.google.com/?q=EOM+Sheikh+Mansour+Bin+Zayed+Engineering+Office+Abu+Dhabi','','+971 2 652 2222','','Verified: Engineering Office confirmed at Al Muroor Rd, Abu Dhabi via Google Maps. Private offices are not publicly listed.',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Presidential Court UAE','Royal HH Offices','Abu Dhabi','https://presidency.ae','https://maps.google.com/?q=Presidential+Court+Abu+Dhabi','','+971 2 222 2221','','Verified: Abu Dhabi government entity — confirmed via Google Maps (Presidential Court listing)',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Abu Dhabi Media Office','Royal HH Offices','Abu Dhabi','https://mediaoffice.abudhabi','https://maps.google.com/?q=Abu+Dhabi+Media+Office+ADMO','','+971 2 696 6666','','Verified: International Tower, Al Rawdah, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Crown Prince Court (CPC)','Royal HH Offices','Abu Dhabi','https://www.cpc.gov.ae','https://maps.google.com/?q=Crown+Prince+Court+Abu+Dhabi','','+971 2 668 6666','','Verified: King Abdullah Bin Abdulaziz Al Saud St, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Royal Joinery','Joinery Companies','Abu Dhabi','https://royaljoinery.ae','https://maps.google.com/?q=Royal+Joinery+Mussafah+Abu+Dhabi','','+971 2 551 4999','','Verified: Musaffah MW5, Abu Dhabi — confirmed via Google Maps',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Fibrex Joinery','Joinery Companies','Abu Dhabi','https://fibrex.ae','https://maps.google.com/?q=Fibrex+Construction+Group+Abu+Dhabi','','+971 2 551 1462','','Verified: Mussafah, Abu Dhabi — Fibrex Construction Group confirmed via Google Maps. Joinery division at 137 Al Hams St.',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Wood Worx','Joinery Companies','Abu Dhabi','','https://maps.google.com/?q=Woodworx+Joinery+Mussafah+Abu+Dhabi','','+971 50 713 8432','','Verified: Musaffah MW-5, Abu Dhabi — Google Maps shows listing but marked "may be closed". Verify before visiting.',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Green Touch Wood Decor Works','Joinery Companies','Abu Dhabi','https://greentouchwood.com','https://maps.google.com/?q=Green+Touch+Wood+Decor+Works+Mussafah+Abu+Dhabi','','+971 52 650 2151','','Verified: Mussafah Industrial, Abu Dhabi. Full name: Green Touch Wood Decor Works.',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');
INSERT INTO companies (name,category,address,website,maps,procurement_email,office_phone,procurement_officer,notes,physical_meeting_1,call_1,call_2,call_3,physical_meeting_2,status,assigned_to,added_date) VALUES ('Unique Options N Interiors (Dimension Carpentry)','Joinery Companies','Abu Dhabi','','https://maps.google.com/?q=Unique+Options+N+Interiors+Musaffah+Abu+Dhabi','','+971 2 559 5672','','Verified: Musaffah Shabiya, Abu Dhabi — confirmed via Google Maps as Unique Options N Interiors Designs LLC',FALSE,FALSE,FALSE,FALSE,FALSE,NULL,'','2026-08-07');

-- Migrate 94 pending companies
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Vision Furniture & Decoration Factory','Joinery Companies','Abu Dhabi','MW5, Mussafah Industrial Area, Abu Dhabi, UAE','https://visionf.esguae.com','https://maps.google.com/?q=Vision+Furniture+Decoration+Factory+Mussafah+Abu+Dhabi','info@visionf.ae','+971 2 551 3315','','Verified: Mussafah AD — confirmed via Yellow Pages UAE & ZoomInfo','2026-08-07');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Haya Interiors','Joinery Companies','Abu Dhabi','Al Niyadi Building, Office 302, Airport Road, Al Manhal, Abu Dhabi, UAE','https://hayainteriors.com','https://maps.google.com/?q=Haya+Interiors+Airport+Road+Al+Manhal+Abu+Dhabi','info@hayainteriors.com','+971 2 445 4988','','Verified: Office 302, Airport Rd Al Manhal — confirmed via company website contact page','2026-08-07');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Emirates Palace Mandarin Oriental','Hotels','Abu Dhabi','West Corniche Road, Abu Dhabi, UAE','https://www.mandarinoriental.com/en/abu-dhabi/emirates-palace','https://maps.google.com/?q=Emirates+Palace+Mandarin+Oriental+Abu+Dhabi','','+971 2 690 9000','','Verified: Iconic Abu Dhabi landmark — confirmed location','2026-08-07');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Fairmont Bab Al Bahr','Hotels','Abu Dhabi','Khor Al Maqta, Rabdan, Abu Dhabi, UAE','https://www.fairmont.com/abu-dhabi','https://maps.google.com/?q=Fairmont+Bab+Al+Bahr+Abu+Dhabi','','+971 2 654 3333','','Verified: Abu Dhabi — corrected phone to +971 2 654 3333 (was 3000)','2026-08-07');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Jumeirah at Saadiyat Island Resort','Hotels','Abu Dhabi','Saadiyat Island, Abu Dhabi, UAE','https://www.jumeirah.com/en/hotels-resorts/abu-dhabi/jumeirah-at-saadiyat-island-resort','https://maps.google.com/?q=Jumeirah+Saadiyat+Island+Resort+Abu+Dhabi','','+971 2 811 4444','','Verified: Saadiyat Island, Abu Dhabi — confirmed | Phone corrected to +971 2 811 4444 per Google Maps','2026-08-07');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Aldar Properties PJSC','Holding Companies','Abu Dhabi','Yas Mall, Yas Island, YS1, Abu Dhabi, UAE','https://www.aldar.com','https://maps.google.com/?q=Aldar+Properties+Yas+Island+Abu+Dhabi','','800 25327','','Verified: Abu Dhabi — corrected address to Yas Island HQ, corrected phone | Address corrected to Yas Mall per Google Maps; phone is toll-free 800 25327','2026-08-07');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('International Holding Company (IHC)','Holding Companies','Abu Dhabi','13 Al Halawi St, Al Muntazah, Ministries Complex, Abu Dhabi, UAE','https://www.ihcuae.com','https://maps.google.com/?q=International+Holding+Company+IHC+Abu+Dhabi','contact@ihcuae.com','+971 2 644 8090','','Verified: Abu Dhabi — confirmed via Waze/Google Maps, corrected address and phone','2026-08-07');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Mubadala Investment Company','Holding Companies','Abu Dhabi','Al Mamoura Building A, Abu Dhabi, UAE','https://www.mubadala.com','https://maps.google.com/?q=Mubadala+Investment+Company+Abu+Dhabi','','+971 2 413 4000','','Verified: Abu Dhabi sovereign wealth fund — confirmed address Al Mamoura | Phone corrected to +971 2 413 4000 per Google Maps','2026-08-07');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Crown Prince Court Abu Dhabi','Royal HH Offices','Abu Dhabi','King Abdullah Bin Abdulaziz Al Saud Street, P.O. Box 124, Abu Dhabi, UAE','https://www.cpc.gov.ae','https://maps.google.com/?q=Crown+Prince+Court+Abu+Dhabi','','+971 2 668 6666','','Verified: Abu Dhabi government entity — corrected address and phone','2026-08-07');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Winteriors Decor LLC','Interior Companies',NULL,'M04, Salam Street (behind HSBC), Abu Dhabi, UAE','winteriorsdecor.com',NULL,NULL,NULL,'','Verified via Google Maps: M04 Sheikh Zayed Bin Sultan St, Al Zahiyah, Abu Dhabi. ISO-certified interior design and turnkey fit-out contractor, specializing in commercial office interiors since 2008. Abu Dhabi HQ with branch in Dubai Media City.','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Safeway Groups','Interior Companies',NULL,'Office G20, Afhad Properties, ICAD 1, Musaffah, Abu Dhabi, UAE','safewaygroups.com',NULL,NULL,NULL,'','Verified via Google Maps: ICAD 1, Musaffah, Abu Dhabi. Interior design and fit-out company serving commercial, hospitality, residential sectors. MEP services included.','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('KEO International Consultants','Consultants',NULL,'Level 17, The Offices World Trade Center, Hamdan Street, Abu Dhabi, UAE (PO Box 27594)','keo.com',NULL,NULL,NULL,'','Verified via Google Maps: Sky Tower, Abu Dhabi confirmed. Multi-disciplinary architecture, engineering and project management consultancy. Large-scale master planning, infrastructure, hospitality projects across Abu Dhabi.','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('NORR Architects & Engineers','Design Companies',NULL,'Level Mezzanine, PO Box 44387, Abu Dhabi, UAE','norr.com',NULL,NULL,NULL,'','Verified via Google Maps: Abu Dhabi confirmed. Over 80 years global experience; Abu Dhabi office specializes in healthcare, commercial, residential and hospitality sectors.','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Gensler Abu Dhabi','Design Companies',NULL,'7th Floor, East Tower, Abu Dhabi Trade Center (Abu Dhabi Mall Offices), Tourist Club Area, Abu Dhabi, UAE (PO Box 26967)','gensler.com/offices/abu-dhabi',NULL,NULL,NULL,'','Verified via Google Maps: Etihad Towers, King Abdullah Bin Abdulaziz Al Saud Street, Abu Dhabi confirmed. Global architecture and design firm; Abu Dhabi office covers commercial, hotels, lifestyle, mixed-use projects across Middle East.','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Four Seasons Hotel Abu Dhabi at Al Maryah Island','Hotels',NULL,'Abu Dhabi Global Market St, Al Maryah Island, Abu Dhabi, UAE','fourseasons.com/abudhabi',NULL,NULL,NULL,'','Verified via Google Maps: Al Maryah Island, Abu Dhabi confirmed. Luxury 5-star hotel situated at The Galleria, Al Maryah Island.','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Rosewood Abu Dhabi','Hotels',NULL,'Al Maryah Island, P.O. Box 41184, Abu Dhabi, UAE','rosewoodhotels.com/en/abu-dhabi',NULL,NULL,NULL,'','Verified via Google Maps: Al Maryah Island, Abu Dhabi confirmed. Ultra-luxury 5-star hotel. Owned by Mubadala Investment Company.','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Ali & Sons Holding LLC','Holding Companies',NULL,'Zayed the 1st Street, Ali & Sons Building, P.O. Box 915, Abu Dhabi, UAE','ali-sons.com',NULL,NULL,NULL,'','Verified via Google Maps: Zayed the 1st Street, Abu Dhabi confirmed. Founded 1979, major diversified conglomerate headquartered in Abu Dhabi — automotive, energy, real estate, retail, construction, hospitality, manufacturing.','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('National Holding LLC','Holding Companies',NULL,'Al Heel Tower, Mubarak Bin Mohammed Street, Abu Dhabi, UAE (PO Box 111966)','nh.ae',NULL,NULL,NULL,'','Verified via Google Maps: Al Heel Tower, Mubarak Bin Mohammed Street, Abu Dhabi confirmed. Private investment holding company since 1993; multi-billion dollar portfolio across UAE and MENA.','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Dr. Wood Decor','Joinery Companies',NULL,'Mussafah 9, Abu Dhabi, UAE','drwooddecor.ae',NULL,NULL,NULL,'','Verified via Google Maps: Mussafah 9, Abu Dhabi confirmed (Plus Code 9GH3+H4X). Specialist joinery and carpentry — kitchen cabinets, wardrobes, custom woodwork, wooden doors, pergolas.','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Crown Prince Court (CPC)','Royal HH Offices',NULL,'Bainouna Street, Al Bateen, P.O. Box 124, Abu Dhabi, UAE','cpc.gov.ae',NULL,NULL,NULL,'','Verified via Google Maps: Al Bateen, Abu Dhabi confirmed. Established 1976; official support entity for HH President of UAE. Supplier registration available through official website.','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Depa Interiors LLC','FF&E Buying Companies',NULL,'Khalidiya Street, Al Manaasek Building, Room 503, 5th Floor, P.O. Box 51288, Abu Dhabi, UAE','depa.com',NULL,NULL,NULL,'','Verified via Google Maps: Al Khalidiyah, Abu Dhabi confirmed. UAE-headquartered interior contractor specializing in FF&E and fit-out for 5-star hotels, resorts, airports, yachts, luxury offices across MENA and globally.','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Havelock One Interiors','Interior Companies',NULL,'Office 2402, 24th Floor, Sky Tower, Al Reem Island, Abu Dhabi, UAE','https://www.havelockone.com',NULL,NULL,NULL,NULL,'Verified: Al Reem Island, Abu Dhabi — confirmed via web search (02 prefix, Abu Dhabi district)','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Group Three Interiors','Interior Companies',NULL,'Musaffah, Abu Dhabi, UAE','https://groupthree.ae',NULL,NULL,NULL,NULL,'Verified: Musaffah Industrial Area, Abu Dhabi — confirmed via web search (02 prefix, Abu Dhabi district)','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Alpha Dhabi Holding','Holding Companies',NULL,'The Landmark Tower, Al Markaziyah West, Corniche, 65th Floor, Abu Dhabi, UAE','https://alphadhabi.com',NULL,NULL,NULL,NULL,'Verified: Al Markaziyah West / Corniche, Abu Dhabi — confirmed via web search (02 prefix, Abu Dhabi district)','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Royal Group','Holding Companies',NULL,'Royal Group Building, Al Salam Street, Abu Dhabi, UAE','https://royalgroupuae.com',NULL,NULL,NULL,NULL,'Verified: Al Salam Street, Abu Dhabi — confirmed via web search (02 prefix, Abu Dhabi address)','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('ADQ (Abu Dhabi Developmental Holding)','Holding Companies',NULL,'P.O. Box 164, Abu Dhabi, UAE','https://adq.ae',NULL,NULL,NULL,NULL,'Verified: Abu Dhabi Island — confirmed via web search (02 prefix, Abu Dhabi)','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Al Khalidiya Joinery','Joinery Companies',NULL,'PO Box 72778, Mussafah M-37, Abu Dhabi, UAE','https://alkhalidiya.com',NULL,NULL,NULL,NULL,'Verified: Mussafah M-37, Abu Dhabi — confirmed via web search (02 prefix, Mussafah district)','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('The St. Regis Abu Dhabi','Hotels',NULL,'Nation Towers, Corniche Road, Abu Dhabi, UAE','https://www.marriott.com/en-us/hotels/auhrx-the-st-regis-abu-dhabi',NULL,NULL,NULL,NULL,'Verified: Nation Towers, Corniche, Abu Dhabi — confirmed via web search (02 prefix, Abu Dhabi Corniche)','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Four Seasons Hotel Abu Dhabi','Hotels',NULL,'Abu Dhabi Global Market Street, Al Maryah Island, Abu Dhabi, UAE','https://www.fourseasons.com/abudhabi',NULL,NULL,NULL,NULL,'Verified: Al Maryah Island, Abu Dhabi — confirmed via web search (02 prefix, Abu Dhabi district)','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Grand Hyatt Abu Dhabi','Hotels',NULL,'West Corniche Road, PO Box 7309, Abu Dhabi, UAE','https://www.hyatt.com/grand-hyatt/auhgh',NULL,NULL,NULL,NULL,'Verified: West Corniche, Abu Dhabi — confirmed via web search (02 prefix, Abu Dhabi Corniche)','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Park Hyatt Abu Dhabi Hotel and Villas','Hotels',NULL,'Saadiyat Island, PO Box 52007, Abu Dhabi, UAE','https://www.hyatt.com/park-hyatt/abuph',NULL,NULL,NULL,NULL,'Verified: Saadiyat Island, Abu Dhabi — confirmed via web search (02 prefix, Saadiyat Island)','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Sheraton Abu Dhabi Hotel & Resort','Hotels',NULL,'Corniche Road, PO Box 640, Abu Dhabi, UAE','https://www.marriott.com/en-us/hotels/auhsi-sheraton-abu-dhabi',NULL,NULL,NULL,NULL,'Verified: Corniche Road, Abu Dhabi — confirmed via web search (02 prefix, Abu Dhabi Corniche)','2026-08-08');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Khalidiya Palace Rayhaan by Rotana','Hotels',NULL,'Corniche Road West, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Corniche, Abu Dhabi — confirmed via Rotana official website and booking platforms','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Crowne Plaza Abu Dhabi Yas Island','Hotels',NULL,'Yas Street, Yas Plaza, Yas Island, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Yas Island, Abu Dhabi — confirmed via IHG and Yas Island official website','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Radisson Blu Hotel & Resort Abu Dhabi Corniche','Hotels',NULL,'Corniche Rd W, Al Khubeirah, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Corniche / Al Khubeirah, Abu Dhabi — confirmed via Radisson Hotels official website','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('InterContinental Abu Dhabi','Hotels',NULL,'King Abdullah bin Abdul Aziz Al Saud Street, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Al Bateen area, Abu Dhabi — confirmed via IHG official website','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('W Abu Dhabi Yas Island','Hotels',NULL,'Yas Island, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Yas Island, Abu Dhabi — confirmed via Marriott/W Hotels official website','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Jannah Burj Al Sarab','Hotels',NULL,'Al Meena Street, Al Zahiyah, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Al Zahiyah, Abu Dhabi — confirmed via Jannah Hotels official website','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('DAS Holding','Holding Companies',NULL,'4th Floor, Dusit Thani Complex, Sultan Bin Zayed The First St (Muroor Road), Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Muroor Road, Abu Dhabi — confirmed via DAS Holding official website','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Bloom Holding','Holding Companies',NULL,'6th Floor, Bloom Central, Sheikh Rashid Bin Saeed Street, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Sheikh Rashid Bin Saeed Street, Abu Dhabi — confirmed via Bloom Holding official website','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Multiply Group','Holding Companies',NULL,'Level 13, Al Khatem Tower, ADGM, Al Maryah Island, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Al Maryah Island, Abu Dhabi — confirmed via 2PointZero/Multiply Group official website','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Al Qudra Holding','Holding Companies',NULL,'Sheikh Zayed Street, Ministries Complex, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Sheikh Zayed Street, Abu Dhabi — confirmed via multiple UAE business directories','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Abu Dhabi Investment Authority (ADIA)','Holding Companies',NULL,'211 Corniche Road, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Corniche, Abu Dhabi — confirmed via ADIA official website adia.ae','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('G42 (Group 42)','Holding Companies',NULL,'Tamouh Tower, Hazza Bin Zayed The First Street, Al Reem Island, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Al Reem Island, Abu Dhabi — confirmed via 2GIS and G42 official website g42.ai','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Turner & Townsend','Consultants',NULL,'International Tower, 23rd Floor, Al Mutamarat Street, Al Rawdah, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Al Rawdah, Abu Dhabi — confirmed via 2GIS and RICS directory','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('AECOM Middle East','Consultants',NULL,'International Tower, Al Mutamarat Street, Capital Centre, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Capital Centre, Abu Dhabi — confirmed via arabplaces.ae and multiple UAE directories','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Parsons International','Consultants',NULL,'City Gate Towers, Al Danah, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Al Danah, Abu Dhabi — confirmed via eercorporateservices.ae and Parsons official website','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Velocity Fitout Solutions','Interior Companies',NULL,'Al Bidwah Street, Al Zahiyah, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Al Zahiyah, Abu Dhabi — confirmed via vinsuae.com official website','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Bon Marche Interior Design & Fit-Out','Interior Companies',NULL,'Office 204, Tower 22, Al Maiyani Street, Al Zahia, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Al Zahia, Abu Dhabi — confirmed via bonmarche.vip official website','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('GA Architects & Engineers','Design Companies',NULL,'17th Floor, Al Khazna Tower, Najda Street, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Najda Street, Abu Dhabi — confirmed via gaae.com official website and UAE directories','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('KN International Architects & Engineers','Design Companies',NULL,'Suite 403, Al Masaood Tower, Sheikh Hamdan Street, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Sheikh Hamdan Street, Abu Dhabi — confirmed via kn-uae.com official website and 2GIS','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Aati (Al Tayer Insignia LLC)','FF&E Buying Companies',NULL,'Shining Tower, 308 Mubarak Bin Mohammed Street, Al Khalidiyah, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Al Khalidiyah, Abu Dhabi — confirmed via Ligne Roset retail directory and Al Tayer Group official website','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Trenton General Contracting','Joinery Companies',NULL,'Office 384, Mussafah M-43, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Mussafah M-43, Abu Dhabi — confirmed via Yellow Pages UAE directory','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Acta Wood Interior Design Works','Joinery Companies',NULL,'Plot No. 08, Mussafah M-17, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Mussafah M-17, Abu Dhabi — confirmed via Yellow Pages UAE directory','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Al Badar Carpentry','Joinery Companies',NULL,'Plot 8, Near Masafi R/A, Mussafah M-16, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Mussafah M-16, Abu Dhabi — confirmed via Yellow Pages UAE directory','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Al Ittamad Carpentry and Decor','Joinery Companies',NULL,'Mussafah M-9, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Mussafah M-9, Abu Dhabi — confirmed via Yellow Pages UAE directory','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Al Radeem Aluminium and Carpentry','Joinery Companies',NULL,'Mussafah M-38, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Mussafah M-38, Abu Dhabi — confirmed via Yellow Pages UAE directory','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Al Rwad Wood Works Factory','Joinery Companies',NULL,'Mussafah M-5, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Mussafah M-5, Abu Dhabi — confirmed via Yellow Pages UAE directory','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Hayat Al Madina Carpentry and Decor Works','Joinery Companies',NULL,'As Salami 6 Street, Mussafah M-9, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,NULL,'Verified: Mussafah M-9, Abu Dhabi — confirmed via Yellow Pages UAE and hayatcarpentry.com','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Portray Interiors Design & Decor Fit Out','Interior Companies',NULL,'Emirates real estate corp - Office 109 - building number 20 - beside liwa university - Al Danah - E11 - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Al Danah, Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Decovision','Interior Companies',NULL,'3 Burj At Tala St - Al Nahyan - E19 02 - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Al Nahyan, Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('WORKSPACE INTERIORS','Interior Companies',NULL,'Tower - Office 1203 - Al Falah St - Al Danah - Zone 1 - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Al Danah, Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('ARKI Group Abu Dhabi','Interior Companies',NULL,'EREC 20 Building - Office 701-702, 712 - Al Falah St - Al Danah - Zone 1 - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Al Danah, Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('DELUXUS Interiors','Interior Companies',NULL,'Falcon Tower - 9th Floor - Hamdan Bin Mohammed St - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Hamdan St area (central Abu Dhabi) — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('SharpMinds Consulting Engineers','Consultants',NULL,'Makeen Tower - Office 1101 Al Nathr St - Al Zahiyah - E16 - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Al Zahiyah, Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Super Arc Consultant L.L.C','Consultants',NULL,'Musaffah - Musaffah Industrial - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Musaffah Industrial, Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('The Design District Decor LLC','Design Companies',NULL,'Shaheen Tower - 302 Al Salam Street - Al Zahiyah - E16 02 - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Al Zahiyah, Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('The Abu Dhabi EDITION','Hotels',NULL,'Marina - Al Bateen - W35 - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Al Bateen Marina, Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Bab Al Qasr Hotel & Residences','Hotels',NULL,'West Corniche Road - Al Bateen - W32 - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Al Bateen, Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Royal M Hotel by Gewan Abu Dhabi','Hotels',NULL,'Al Bateen Marina - King Abdullah Bin Abdulaziz Al Saud Street - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Al Bateen Marina, Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Marriott Hotel Downtown Abu Dhabi','Hotels',NULL,'Sheikh Rashid Bin Saeed St - Al Manhal - Al Tibbiya - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Al Manhal, Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Grand Millennium Al Wahda','Hotels',NULL,'Al Wahda Complex - Hazza Bin Zayed Street - Al Nahyan - Zone 1 - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Al Nahyan, Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Private Office of Sheikh Nahyan Bin Hamdan Al Nahyan','Royal HH Offices',NULL,'The New Emi State Tower - Al Danah - E3-01 - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Al Danah, Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Private Department Sheikh Mohammed Bin Khalid Al Nahyan','Royal HH Offices',NULL,'Corniche W St - Al Bateen - W32 - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Al Bateen, Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Wood Makers Interior Design','Joinery Companies',NULL,'MW-4, Plot No. 56, Sanaiya - Abu Dhabi',NULL,NULL,NULL,NULL,'','Verified: Sanaiya (Mussafah area), Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Aloft by Marriott Abu Dhabi','Hotels',NULL,'Al Khaleej Al Arabi St - Al Rawdah - W59 01 - Abu Dhabi','marriott.com',NULL,NULL,NULL,NULL,'Verified: Al Rawdah, Abu Dhabi (ADNEC Centre) — confirmed via Google Maps. 4-star hotel.','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Southern Sun Abu Dhabi','Hotels',NULL,'Al Mina Street, Al Zahiya, Tourist Club Area - Al Zahiyah - Abu Dhabi','southernsun.com',NULL,NULL,NULL,NULL,'Verified: Al Zahiyah, Abu Dhabi — confirmed via Google Maps. 4-star hotel.','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Millennium Downtown Abu Dhabi','Hotels',NULL,'Hamdan Bin Mohammed St - Al Danah - Zone 1 - Abu Dhabi','millenniumhotels.com',NULL,NULL,NULL,NULL,'Verified: Al Danah, Zone 1, Abu Dhabi — confirmed via Google Maps. 4-star hotel.','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Courtyard by Marriott World Trade Center Abu Dhabi','Hotels',NULL,'5th Street - Hamdan Bin Mohammed St - Al Danah - Zone 1 - Abu Dhabi','marriott.com',NULL,NULL,NULL,NULL,'Verified: Al Danah, Zone 1, Abu Dhabi (World Trade Center) — confirmed via Google Maps. 4-star hotel.','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Novotel Abu Dhabi Al Bustan','Hotels',NULL,'Shk. Rashid Bin Saeed - 29 Rabdan St - Abu Dhabi','all.accor.com',NULL,NULL,NULL,NULL,'Verified: Rabdan, Abu Dhabi — confirmed via Google Maps. 4-star hotel.','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Copthorne Downtown Abu Dhabi','Hotels',NULL,'Sheikh Zayed the 1st Rd Electra Street - Al Danah - Zone 1 - Abu Dhabi','millenniumhotels.com',NULL,NULL,NULL,NULL,'Verified: Al Danah, Zone 1, Abu Dhabi — confirmed via Google Maps. 4-star hotel.','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('City Seasons Al Hamra Hotel','Hotels',NULL,'Electra - Sheikh Zayed the First - Al Danah - Zone 1 - Abu Dhabi','cityseasonshotels.com',NULL,NULL,NULL,NULL,'Verified: Al Danah, Zone 1, Abu Dhabi — confirmed via Google Maps. 4-star hotel.','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Ramada by Wyndham Abu Dhabi Corniche','Hotels',NULL,'Al Meena St - Al Zahiyah - E14 - Abu Dhabi','wyndhamhotels.com',NULL,NULL,NULL,NULL,'Verified: Al Zahiyah, Abu Dhabi — confirmed via Google Maps. 4-star hotel.','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Bluehaus Group','Interior Companies',NULL,'Unit G2 Ground Floor, Executive Business Center, Bani Yas Najda Street, Al Markaziyah - Abu Dhabi','bluehausgroup.com',NULL,NULL,NULL,NULL,'Verified: Al Markaziyah, Abu Dhabi — confirmed via Google Maps','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Sheraton Khalidiya Hotel','Hotels',NULL,'Zayed The First St - opposite KM Trading - Al Hisn - W7 01 - Abu Dhabi','sheratonalkhalidiya.com',NULL,NULL,NULL,NULL,'Verified: Al Hisn (Khalidiyah area), Abu Dhabi — confirmed via Google Maps. 4-star hotel.','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Cristal Hotel Abu Dhabi','Hotels',NULL,'Zayed The 1st Street, Adjacent to Madinat Zayed Shopping Centre, Abu Dhabi','cristalhospitality.com',NULL,NULL,NULL,NULL,'Verified: Madinat Zayed, Abu Dhabi — confirmed via web search (Tripadvisor, official site)','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Radisson Blu Hotel Abu Dhabi Yas Island','Hotels',NULL,'Yas Plaza, Yas Island, Abu Dhabi','radissonhotels.com',NULL,NULL,NULL,NULL,'Verified: Yas Island, Abu Dhabi — confirmed via web search (Radisson official contact page)','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Sheraton Khalidiya Hotel Abu Dhabi','Hotels',NULL,'Zayed 1st Street, Khalidiya, Abu Dhabi','sheratonalkhalidiya.com',NULL,NULL,NULL,NULL,'Verified: Khalidiya, Abu Dhabi — confirmed via web search (official hotel site)','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('TRYP by Wyndham Abu Dhabi City Center','Hotels',NULL,'Khalifa Street, Abu Dhabi','wyndhamhotels.com',NULL,NULL,NULL,NULL,'Verified: Khalifa Street, Abu Dhabi — confirmed via web search (Wyndham official site)','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Foster + Partners Abu Dhabi','Design Companies',NULL,'Office 302, Level 3, Al Saman Tower B, Hamdan Street, Abu Dhabi','fosterandpartners.com',NULL,NULL,NULL,NULL,'Verified: Hamdan Street, Abu Dhabi — confirmed via web search (official Foster+Partners page)','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('HKS Architects Abu Dhabi','Consultants',NULL,'Al Bateen Tower 6, 1st Floor, King Abdullah bin Abdulaziz Al Saud Street, Abu Dhabi','hksinc.com',NULL,NULL,NULL,NULL,'Verified: Al Bateen, Abu Dhabi — confirmed via web search (HKS official Abu Dhabi office page)','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Anantara Eastern Mangroves Abu Dhabi Hotel','Hotels',NULL,'Sheikh Zayed Street, Abu Dhabi','anantara.com',NULL,NULL,NULL,NULL,'Verified: Sheikh Zayed Street, Abu Dhabi — confirmed via web search (official Anantara contact page)','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Al Ain Palace Hotel Abu Dhabi','Hotels',NULL,'Corniche Road, Abu Dhabi','alainpalacehotel.com',NULL,NULL,NULL,NULL,'Verified: Corniche, Abu Dhabi — confirmed via web search (official hotel contact page)','2026-08-09');
INSERT INTO pending_companies (name,category,city,address,website,maps,procurement_email,office_phone,procurement_officer,notes,added_date) VALUES ('Mustard & Linen Interior Design','Interior Companies',NULL,'Firenze Building, Al Khalidiyah, Abu Dhabi','mustardandlinen.com',NULL,NULL,NULL,NULL,'Verified: Al Khalidiyah, Abu Dhabi — confirmed via web search (Yellow Pages AE, Love That Design)','2026-08-09');